const STOCK_TYPES = {
  INGREDIENT: "ingredient",
  CONSOMMABLE: "consommable",
  PERISSABLE: "perissable",
  MATERIEL: "materiel",
  EMBALLAGE: "emballage",
};
export const liste = [
  // ============= INGREDIENTS - ÉPICES =============
  {
    id: "ing-epice-001",
    denomination: "Sel de cuisine",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Sel fin pour assaisonnement général",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-002",
    denomination: "Piment rouge moulu",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Piment fort moulu pour relever les plats",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-003",
    denomination: "Ail frais",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Gousses d'ail frais pour aromatisation",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-004",
    denomination: "Oignon",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Oignons frais pour base de cuisson",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-005",
    denomination: "Poivre noir moulu",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Poivre noir finement moulu",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-006",
    denomination: "Crevette séchée moulue",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Poudre de crevettes séchées pour assaisonnement",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-007",
    denomination: "Gingembre frais",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Racine de gingembre frais",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-008",
    denomination: "Citronnelle",
    unite: {
      nom: "botte",
      symbol: "botte",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Tiges de citronnelle fraîche",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-009",
    denomination: "Citron",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Citrons frais pour jus et zeste",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-epice-010",
    denomination: "Sucre en poudre",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Sucre blanc raffiné",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= INGREDIENTS - LÉGUMES =============
  {
    id: "ing-leg-001",
    denomination: "Haricots verts",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Haricots verts frais",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-002",
    denomination: "Carottes",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Carottes fraîches",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-003",
    denomination: "Poivron",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Poivrons multicolores",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-004",
    denomination: "Tomates fraîches",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Tomates mûres pour sauces et salades",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-005",
    denomination: "Persil frais",
    unite: {
      nom: "botte",
      symbol: "botte",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Persil plat pour garniture",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-006",
    denomination: "Laitue",
    unite: {
      nom: "pièce",
      symbol: "pce",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Laitue verte pour salades",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-leg-007",
    denomination: "Échalotes",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Échalotes pour aromatisation fine",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= INGREDIENTS - FRUITS =============
  {
    id: "ing-fruit-001",
    denomination: "Mangue",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Mangues mûres pour desserts et jus",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-fruit-002",
    denomination: "Banane",
    unite: {
      nom: "régime",
      symbol: "rég",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Bananes plantains et douces",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= INGREDIENTS - VIANDES =============
  {
    id: "ing-viande-001",
    denomination: "Viande de bœuf",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Viande de bœuf fraîche découpée",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-viande-002",
    denomination: "Poulet entier",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Poulet frais prêt à découper",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-viande-003",
    denomination: "Viande de mouton",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Viande de mouton avec os",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "ing-viande-004",
    denomination: "Viande de lapin",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Lapin frais découpé",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= INGREDIENTS - POISSON =============
  {
    id: "ing-poisson-001",
    denomination: "Sardines fraîches",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Sardines fraîches du jour",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= INGREDIENTS - GRAINS =============
  {
    id: "ing-grain-001",
    denomination: "Sorgho",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Grains de sorgho pour préparations traditionnelles",
    type: STOCK_TYPES.INGREDIENT,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= CONSOMMABLES =============
  {
    id: "cons-001",
    denomination: "Pain simple",
    unite: {
      nom: "pièce",
      symbol: "pce",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Pain blanc standard",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-002",
    denomination: "Pain viennois",
    unite: {
      nom: "pièce",
      symbol: "pce",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Pain viennois moelleux",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-003",
    denomination: "Farce viande bœuf",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Farce de bœuf préparée et assaisonnée",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-004",
    denomination: "Farce poisson",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Farce de poisson blanc assaisonnée",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-005",
    denomination: "Farce viande mouton",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Farce de mouton épicée",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-006",
    denomination: "Farce viande lapin",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Farce de lapin aux herbes",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-007",
    denomination: "Farce viande poulet",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Farce de poulet légèrement épicée",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-008",
    denomination: "Sauce vinaigrette",
    unite: {
      nom: "litre",
      symbol: "L",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Vinaigrette maison préparée",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-009",
    denomination: "Huile d'arachide",
    unite: {
      nom: "litre",
      symbol: "L",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Huile d'arachide pour friture et cuisson",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-010",
    denomination: "Yaourt nature",
    unite: {
      nom: "pot",
      symbol: "pot",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Yaourt nature fait maison",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "cons-011",
    denomination: "Dèguè",
    unite: {
      nom: "litre",
      symbol: "L",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Boisson traditionnelle à base de mil et yaourt",
    type: STOCK_TYPES.CONSOMMABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= MATÉRIEL - APPAREILS =============
  {
    id: "mat-app-001",
    denomination: "Mixeur Moulinex",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Mixeur professionnel Moulinex 1500W",
    type: STOCK_TYPES.MATERIEL,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= MATÉRIEL - USTENSILES =============
  {
    id: "mat-ust-001",
    denomination: "Cuillères de service",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Cuillères en inox pour service",
    type: STOCK_TYPES.MATERIEL,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mat-ust-002",
    denomination: "Louche de cuisine",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Louches en inox de différentes tailles",
    type: STOCK_TYPES.MATERIEL,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mat-ust-003",
    denomination: "Pinces de cuisine",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Pinces multiusages en inox",
    type: STOCK_TYPES.MATERIEL,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= MATÉRIEL - AUTRES =============
  {
    id: "mat-autre-001",
    denomination: "Serviettes de table",
    unite: {
      nom: "paquet",
      symbol: "pqt",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Serviettes en papier double épaisseur",
    type: STOCK_TYPES.MATERIEL,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= EMBALLAGE =============
  {
    id: "emb-001",
    denomination: "Cuillères jetables",
    unite: {
      nom: "paquet de 100",
      symbol: "pqt",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Cuillères plastique jetables",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "emb-002",
    denomination: "Box alimentaire",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Boîtes en plastique avec couvercle",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "emb-003",
    denomination: "Papier kraft",
    unite: {
      nom: "rouleau",
      symbol: "rlx",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Papier kraft alimentaire pour emballage",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "emb-004",
    denomination: "Pot de yaourt 250ml",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Pots plastique avec couvercle 250ml",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "emb-005",
    denomination: "Pot de yaourt 500ml",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Pots plastique avec couvercle 500ml",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "emb-006",
    denomination: "Pots de sauce",
    unite: {
      nom: "unité",
      symbol: "u",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Petits pots pour sauces et condiments",
    type: STOCK_TYPES.EMBALLAGE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ============= PÉRISSABLES =============
  {
    id: "per-001",
    denomination: "Mayonnaise",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Mayonnaise industrielle en pot",
    type: STOCK_TYPES.PERISSABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "per-002",
    denomination: "Moutarde",
    unite: {
      nom: "kilogramme",
      symbol: "kg",
    },
    quantite_actuelle: 0,
    imgURL: "",
    description: "Moutarde de Dijon",
    type: STOCK_TYPES.PERISSABLE,
    status: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
